name: Trigger workflow update on change of terminology
on:
  repository_dispatch:
    types: terminology_updated
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger workflow update on change of terminology
        uses: frdrwrt/write-to-file@v1.3
        with:
          # The filename you want to store as csv
          filepath: terminology.csv
          content: ${{ github.event.client_payload.terminology }}
      - name: Use aws cli to import termonology
        run: |
          aws translate list-terminologies --no-paginate