name: Do Something That Needs Scheduled
on:
  repository_dispatch:
    types: terminology_updated
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "termonology: ${{ github.event.client_payload.terminology }}"'
